#ifndef SETTINGSDEFINITIONS_H
#define SETTINGSDEFINITIONS_H

#define SETTINGS_MAINWINDOW_GROUP "mainwindow"
#define SETTINGS_MAINWINDOW_GEO "geometry"
#define SETTINGS_MAINWINDOW_STATE "state"

#endif // SETTINGSDEFINITIONS_H
